name: Run Tests & Generate Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm 

      - name: Ensure package-lock.json Exists
        run: |
          cd web-app
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      - name: Install Dependencies
        run: |
          cd web-app
          npm install --legacy-peer-deps

      - name: Run Tests with Coverage
        run: |
          cd web-app
          npm test -- --coverage --coverageReporters=text --coverageReporters=lcov
