name: Run Tests & Generate Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
            node-version: 20
            registry-url: https://registry.npmjs.org
            cache: pnpm

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Verify pnpm Installation
        run: pnpm --version

      - name: Install Dependencies
        run: |
          cd web-app
          pnpm install --no-frozen-lockfile

      - name: Run Tests with Coverage
        run: |
          cd web-app
          pnpm test --coverage --coverageReporters=text --coverageReporters=lcov
